"""
gen_gateway_secret.py — Generate and write a shared gateway secret.

Run once to wire up authentication between the Signal Manager and
all execution-engine-multi installations that connect to it:

    python gen_gateway_secret.py

Writes the secret to:
  - signal-engine/manager/config.yaml  → gateway_server.secret
  - execution-engine-multi/.env        → SIGNAL_MANAGER_TOKEN=<secret>
    (or prints the value to set manually)

Both sides already read this secret:
  Signal Manager   : gateway_server.secret in config.yaml
  Execution Engine : SIGNAL_MANAGER_TOKEN env var (or signal_manager.token in
                     the agent config generated by ManagerConfig.defaults())
"""

import os
import re
import secrets
import sys
from pathlib import Path

HERE = Path(__file__).parent
SIGNAL_MANAGER_CONFIG = HERE / "config.yaml"
EXEC_ENGINE_ROOT   = HERE.parent.parent / "execution-engine-multi"
EXEC_ENGINE_ENV    = EXEC_ENGINE_ROOT / ".env"
PROGDATA_MANAGER   = Path(os.environ.get("PROGRAMDATA", "C:/ProgramData")) / "Apex Quantel" / "Multi" / "manager"
PROGDATA_ENV       = PROGDATA_MANAGER / ".env"


def _patch_yaml_field(text: str, field: str, value: str) -> str:
    """Replace  field: <anything>  with  field: <value>  in YAML text."""
    pattern = rf"^(\s*{re.escape(field)}:\s*).*$"
    replacement = rf'\g<1>"{value}"'
    updated, n = re.subn(pattern, replacement, text, flags=re.MULTILINE)
    if n == 0:
        raise ValueError(f"Field '{field}' not found in config")
    return updated


def main() -> None:
    token = secrets.token_hex(32)

    # ── Update signal-engine/manager/config.yaml ───────────────────────────
    if not SIGNAL_MANAGER_CONFIG.exists():
        print(f"ERROR: {SIGNAL_MANAGER_CONFIG} not found", file=sys.stderr)
        sys.exit(1)

    text = SIGNAL_MANAGER_CONFIG.read_text(encoding="utf-8")
    text = _patch_yaml_field(text, "secret", token)
    SIGNAL_MANAGER_CONFIG.write_text(text, encoding="utf-8")
    print(f"[OK] Wrote secret to {SIGNAL_MANAGER_CONFIG}")

    env_line = f"SIGNAL_MANAGER_TOKEN={token}\n"

    def _write_env(env_path: Path) -> bool:
        """Upsert SIGNAL_MANAGER_TOKEN in an .env file. Returns True if written."""
        if env_path.exists():
            env_text = env_path.read_text(encoding="utf-8")
            if "SIGNAL_MANAGER_TOKEN" in env_text:
                env_text = re.sub(
                    r"^SIGNAL_MANAGER_TOKEN=.*$", f"SIGNAL_MANAGER_TOKEN={token}",
                    env_text, flags=re.MULTILINE,
                )
            else:
                env_text = env_text.rstrip("\n") + "\n" + env_line
            env_path.write_text(env_text, encoding="utf-8")
            print(f"[OK] Updated {env_path}")
            return True
        else:
            env_path.parent.mkdir(parents=True, exist_ok=True)
            env_path.write_text(env_line, encoding="utf-8")
            print(f"[OK] Created {env_path}")
            return True

    # ── 1. ProgramData manager dir (installed production path) ───────────────
    if PROGDATA_MANAGER.exists() or PROGDATA_ENV.parent.exists():
        _write_env(PROGDATA_ENV)

    # ── 2. Development repo layout ─────────────────────────────────────────
    if EXEC_ENGINE_ROOT.exists():
        _write_env(EXEC_ENGINE_ENV)
    else:
        print(
            f"\nExecution engine repo not found at {EXEC_ENGINE_ROOT}.\n"
            f"Set this env var manually on every host that runs the execution engine:\n\n"
            f"    SIGNAL_MANAGER_TOKEN={token}\n"
        )

    print(
        f"\nDone. Restart both services to apply the new secret.\n"
        f"For remote execution-engine hosts, place this in\n"
        f"  %ProgramData%\\Apex Quantel\\Multi\\manager\\.env\n\n"
        f"    SIGNAL_MANAGER_TOKEN={token}\n"
    )


if __name__ == "__main__":
    main()
